services:
  - type: web
    name: grix
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist/grix/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
